- name: Apt Update & Upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: safe
  tags:
    - always

- name: Ensure dotfiles are up to date
  include: dotfiles.yml

- name: Ensure directories exist
  include: directories.yml