- name: Install tmux
  become: yes
  apt:
    name:
      - tmux
    state: present

- name: Ensure dotfiles are up to date
  include: dotfiles.yml

- name: Back up existing ~/.tmux.conf
  shell: if [ -f ~/.tmux.conf ]; then mv ~/.tmux.conf ~/.tmux.conf.bak ; fi

- name: Link .tmux.conf
  file:
    state: link
    src: "{{ dotfiles_path }}/tmux/dot-tmux.conf"
    dest: ~/.tmux.conf

- name: Install TPM
  git: 
    repo: https://github.com/tmux-plugins/tpm 
    dest: ~/.tmux/plugins/tpm