- name: Apt install shell utils
  become: yes
  apt:
    name:
      - autojump
      - python3-pygments # pygmentize

- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf.git 
    dest: ~/.fzf/
    depth: 1

- name: Install fzf
  shell: ~/.fzf/install