- name: Install vim-gtk
  become: yes
  apt:
    name:
      - vim-gtk
    state: present

- name: Setup variables
  set_fact:
    link_target: "{{ dotfiles_path }}/vim/dot-vimrc"
    backup_path: ~/.vimrc.bak
    config_path: ~/.vimrc

- name: Backup and link vim config
  include: backup_and_link_config.yml

- name: Install vim-plug
  shell: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  args:
    creates: ~/.vim/autoload/plug.vim
