- name: Install zsh and dependencies
  become: yes
  apt:
    name:
      - zsh
      - curl
      - git
      - fonts-powerline
    state: present

- name: Setup variables
  set_fact:
    link_target: "{{ dotfiles_path }}/zsh/dot-zshrc"
    backup_path: ~/.zshrc.bak
    config_path: ~/.zshrc

- name: Backup and link vim config
  include: backup_and_link_config.yml

- name: Install zplug
  shell: test -d ~/.zplug || curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh

- name: Get zsh path
  command: which zsh 
  register: zsh_path

- name: Switch to zsh
  user: 
    name: "{{ ansible_facts['user_id'] }}"
    shell: "{{ zsh_path.stdout }}"
  become: yes 