- name: System upgrade
  include: system-upgrade.yml
  tags:
    - always

- name: Ensure dotfiles are up to date
  include: dotfiles.yml

- name: Ensure directories exist
  include: directories.yml

- name: Install system apps
  include: apps.yml
