- hosts: 127.0.0.1
  connection: local
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  roles:
    - terminal
  tasks:
    - name: All done!
      debug:
        msg:
          - Terminal env setup successfully!