- name: Install apps
  become: no
  community.general.pacman:
    executable: yay
    extra_args: "--builddir {{ansible_user_dir}}/.cache/yay"
    name:
      - stow 
      - topgrade
      - htop
      - xclip
      - ripgrep
    state: present
