- name: Install dependencies
  apt:
    name: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add Docker GPG key
  shell: mkdir -p /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  
- name: Add Docker PPA
  shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: true

- name: Create group named docker
  group:
    name: docker
    state: present

- name: Add user to "docker" group
  user:
    name: "{{ ansible_env.USER }}"
    groups: "docker"
    append: true

- name: Enable Docker Socket
  systemd:
    name: docker.socket
    enabled: true
    state: started