- name: Setup node
  include: node.yml
  tags:
    - node

- name: Setup go
  include: go.yml
  tags:
    - go

- name: Setup elm
  include: elm.yml
  tags:
    - elm

- name: Setup Docker
  include: docker.yml
  become: true
  tags:
    - docker